language: node_js

node_js:
   - "6"
   - "5"
   - "4"

script:
   - istanbul cover --print none --report lcovonly -x test.js test.js

after_success:
   - travis_retry cat ./coverage/lcov.info |coveralls
